### ISSUE TITLE
In open and overdue invoice report (in salesforce) - we need add invoice link column, gl and department

### ISSUE THREAD

**Issue by BroderickErin** [Nimba-Solutions/NYS-Foundations#8]

**Comment by KellyMcMahon1022** [comment]
Kelly also needs a report that shows all paid stripe invoices with the same information (customer name, billing info, product, date, amount, gl, department)

**Comment by carasherwood** [comment]
Edits needed for Paid Report on NYS Hub Home:

- Josh looks like you used used Payment Number instead of Payment ID... (cannot search by that in Stripe.). Needs to be edited to Payment ID (example: pi_3QDADRA3FCW83pV00Yi30yAg)
- Report also missing fields: Invoice Number, Line Items/Products, and Description.
- Metadata fields G/L Code and Dept Code not pulling correctly onto report. Column blank - also should be 2 columns I think.

**Comment by carasherwood** [comment]
Some data in the Paid Report is populating but not all rows. The Current/Overdue Stripe report seems to be working correctly and pulling this data. Maybe a dumb question - why wouldn't the Paid report be the same?

**Comment by carasherwood** [comment]
Noting for product PD Site Leader Institute - the Dept Code is not populating on the Overdue Invoices report. I confirmed in Stripe the metadata is filled in. The G/L code is appearing on the report correctly.

**Comment by PonchoMcGee** [comment]
@carasherwood It is different because of how Stripe associates products to invoices vs direct payments. It is much more difficult to fetch the metadata from these direct card payments. I am planning out how we can map the product and metadata in Salesforce to just handle all reporting on that side instead of using custom code.
